'use server';

/**
 * @fileOverview Implements a Genkit flow for "humanizing" raw AI text output.
 *
 * - humanizeResponse - A function that takes raw text and refines it to be more professional and readable.
 * - HumanizeResponseInput - The input type for the function.
 * - HumanizeResponseOutput - The return type for the function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const HumanizeResponseInputSchema = z.object({
  rawText: z.string().describe('The raw text output from a previous AI model call.'),
});
export type HumanizeResponseInput = z.infer<typeof HumanizeResponseInputSchema>;

const HumanizeResponseOutputSchema = z.object({
  humanizedText: z.string().describe('The refined, human-like text.'),
});
export type HumanizeResponseOutput = z.infer<typeof HumanizeResponseOutputSchema>;


export async function humanizeResponse(input: HumanizeResponseInput): Promise<HumanizeResponseOutput> {
  // If the input is empty or just whitespace, return it directly to avoid unnecessary API calls.
  if (!input.rawText?.trim()) {
    return { humanizedText: input.rawText };
  }
  return humanizeResponseFlow(input);
}

const prompt = ai.definePrompt({
  name: 'humanizeResponsePrompt',
  input: {schema: HumanizeResponseInputSchema},
  output: {schema: HumanizeResponseOutputSchema},
  prompt: `You are an expert information designer and editor. Your primary task is to take the following raw text, which was generated by another AI, and restructure it for maximum clarity and professional presentation.

**Core Directive:** Do not alter the core meaning, facts, or legal substance of the text. Your job is to restructure and reformat the content for human readability.

**Production-Level Formatting Rules (These are MANDATORY):**

1.  **Create Scannable Content:** Break down long, dense paragraphs into shorter, focused ones. Each paragraph should ideally cover a single, distinct idea.
2.  **Enforce Bullet Points:** If you detect any list-like information (e.g., a list of features, items, or points), you MUST format it as a bulleted list (using '•' or '-'). Do not present lists as run-on sentences or dense paragraphs.
3.  **Eliminate All Markdown Asterisks:** You MUST find and remove all markdown-style asterisks ('*' or '**').
    *   For single asterisks indicating a list item, convert it to a clean bullet point on a new line.
    *   For double asterisks used for headings or emphasis (e.g., **Some Heading:**), you MUST remove the asterisks and place the heading on its own new line to give it prominence.
4.  **Preserve Document Headings:** If the input text contains headings that identify a document source (e.g., "From 'Document.pdf':"), you MUST preserve these headings exactly as they are, on their own line, to maintain the separation of information.
5.  **Improve Flow and Tone:** After restructuring, polish the language for a professional and natural tone. Avoid robotic phrasing and ensure smooth transitions between points.

**Raw AI Text to Restructure and Refine:**
{{{rawText}}}
`,
});

const humanizeResponseFlow = ai.defineFlow(
  {
    name: 'humanizeResponseFlow',
    inputSchema: HumanizeResponseInputSchema,
    outputSchema: HumanizeResponseOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
